[package]
name = "matrix_multiplication"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
cli-table = "0.4.7"
rand = "0.8.5"
indicatif = "0.17.7"
rayon = "1.8.0"
